apiVersion: v1
entries:
  my-first-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-06-27T16:44:47.814301029Z"
    description: A Helm chart for Kubernetes
    digest: fe371985d4bde6962c5efaa762cd078670d34d08c6509c1f8dbaa75ef8b3e93e
    name: my-first-chart
    type: application
    urls:
    - https://svengrabic.github.io/test-helm-charts/my-first-chart-0.1.0.tgz
    version: 0.1.0
  my-mysql-chart:
  - apiVersion: v2
    appVersion: 1.17.0
    created: "2024-06-27T16:44:47.814715066Z"
    description: A Helm chart for Kubernetes
    digest: f377b59226b9f5613d5615f87dc37093a78d8ef4d6549e6f8abaea2f12fa4589
    name: my-mysql-chart
    type: application
    urls:
    - https://svengrabic.github.io/test-helm-charts/my-mysql-chart-0.1.0.tgz
    version: 0.1.0
generated: "2024-06-27T16:44:47.812938709Z"
