---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: {{ .Values.version }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root
              key: password
        
        # required for entrypoint when
        # all the custom users are created
        - name: MYSQL_RW_USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-rw
              key: username

        - name: MYSQL_RW_USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-rw
              key: password
        
        - name: MYSQL_GRAFANA_RO_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-grafana-ro
              key: username

        - name: MYSQL_GRAFANA_RO_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-grafana-ro
              key: password
        
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/conf.d/default_auth.cnf
          subPath: default_auth
        - name: mysql-init-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

      - name: mysql-config-volume
        configMap:
          name: mysql-config

      - name: mysql-init-volume
        configMap:
          name: mysql-init
