apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  mysql_config: |
    [client]
    loose-default-character-set = utf8mb4

    [mysqld]
    init_connect                   = 'SET collation_connection = utf8mb4_unicode_ci; SET NAMES utf8mb4;'
    character-set-client-handshake = FALSE
    character-set-server           = utf8mb4
    collation-server               = utf8mb4_unicode_ci
    max_allowed_packet             = 16M
    max_connections                = 2000
    symbolic_links                 = 0
    # Enable this if you have 16 cores or more to improve concurrency
    # table_open_cache_instances     = 16
    transaction-isolation          = READ-COMMITTED
    skip-name-resolve
    safe-user-create                = ON
    local_infile                    = OFF

    # For big setups with a lot of CPU cores you can increase the numbers of read/write threads
    # innodb_read_io_threads              = 16
    # innodb_write_io_threads             = 16
    innodb_file_per_table               = 1
    innodb_buffer_pool_size             = 1G
    innodb_buffer_pool_instances        = 1
    innodb_log_file_size                = 2G
    innodb_log_buffer_size              = 64M
    innodb_flush_log_at_trx_commit      = 2
    innodb_buffer_pool_load_at_startup  = 1
    innodb_buffer_pool_dump_at_shutdown = 1
    innodb_autoinc_lock_mode            = 2
    innodb_flush_method                 = O_DIRECT
    innodb_stats_on_metadata            = 0
    innodb_checksum_algorithm           = crc32
    innodb_thread_concurrency           = 0
    # When the table data is stored on a traditional HDD storage device, flushing
    # such neighbor pages in one operation reduces I/O overhead (primarily for disk
    # seek operations) compared to flushing individual pages at different times.
    # For table data stored on SSD, seek time is not a significant factor and you
    # can turn this setting off to spread out write operations.
    innodb_flush_neighbors              = 0